version: "3.8"
services:
  backend:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - images:/app/src/main/resources/images
    environment:
      DATABASE_HOST: "host.docker.internal"
      DATABASE:PORT: 5432
      DATABASE_NAME: dockerapp_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

volumes:
  images:
